name: UnPack CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Neovim
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Install luarocks
        run: sudo apt-get install -y luarocks

      - name: Install busted
        run: luarocks install busted --local

      - name: Run tests
        run: |
          export PATH=$HOME/.luarocks/bin:$PATH
          export LUA_PATH="?.lua;?/init.lua;./lua/?.lua;./lua/?/init.lua;$HOME/.luarocks/share/lua/5.1/?.lua;$HOME/.luarocks/share/lua/5.1/?/init.lua;./lua_modules/?.lua;./lua_modules/?/init.lua;$LUA_PATH"
          nvim --headless -c "!busted --verbose ." -c "qa!"

  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc and create PR
    steps:
      - uses: actions/checkout@v2

      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}-nvim

      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: docs-update/${{ github.sha }}
          push: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto generate docs"
          branch: docs-update/${{ github.sha }}
          title: "Auto-generated docs"
          body: "This PR updates the vim docs automatically."
          base: main
          draft: false
