name: UnPack CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Neovim
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Install luarocks
        run: sudo apt-get install -y luarocks

      - name: Install busted
        run: luarocks install busted --local

      - name: Run tests
        run: |
          export PATH=$HOME/.luarocks/bin:$PATH
          export LUA_PATH="?.lua;?/init.lua;./lua/?.lua;./lua/?/init.lua;$HOME/.luarocks/share/lua/5.1/?.lua;$HOME/.luarocks/share/lua/5.1/?/init.lua;./lua_modules/?.lua;./lua_modules/?/init.lua;$LUA_PATH"
          nvim --headless -c "!busted --verbose ." -c "qa!"

  docs:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Clone panvimdoc
        run: git clone https://github.com/kdheepak/panvimdoc.git ~/.local/share/panvimdoc

      - name: Generate help doc
        run: |
          mkdir -p doc
          pandoc --lua-filter ~/.local/share/panvimdoc/panvimdoc/panvimdoc.lua \
            README.md -o doc/${{ github.event.repository.name }}.txt

      - name: Commit and push docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add doc/
          git commit -m "chore(docs): update help file"
          git push
        continue-on-error: true
